"""Index non-compact h3 cells to indicate presence of children cells

Revision ID: 1fab309748e6
Revises: 86b462787ba4
Create Date: 2023-11-28 09:53:42.553511

"""
from typing import Sequence, Union

from alembic import op
from app.models import H3Index
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fab309748e6'
down_revision: Union[str, None] = '86b462787ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'h3_children_indicators',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('h3_index', H3Index(), nullable=False),
        sa.Column('dataset_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('dataset_id', 'h3_index')
    )
    op.create_index(op.f('ix_h3_children_indicators_h3_index'), 'h3_children_indicators', ['h3_index'], unique=False)
    op.add_column('datasets', sa.Column('has_compact_only', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'has_compact_only')
    op.drop_index(op.f('ix_h3_children_indicators_h3_index'), table_name='h3_children_indicators')
    op.drop_table('h3_children_indicators')
    # ### end Alembic commands ###
