"""Indicate non-compact-member cells representing a child cell

Revision ID: 2c993f4274d2
Revises: 86b462787ba4
Create Date: 2023-11-24 09:47:39.188773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c993f4274d2'
down_revision: Union[str, None] = '86b462787ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('has_compact_only', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('h3_data', sa.Column('represents_child', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('ix_h3_data_index_represents_child', 'h3_data', ['h3_index', 'represents_child'], unique=False)
    op.create_index(op.f('ix_h3_data_represents_child'), 'h3_data', ['represents_child'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_h3_data_represents_child'), table_name='h3_data')
    op.drop_index('ix_h3_data_index_represents_child', table_name='h3_data')
    op.drop_column('h3_data', 'represents_child')
    op.drop_column('datasets', 'has_compact_only')
    # ### end Alembic commands ###
