"""Add uid, date validity, url, and accessibility fields for datasets

Revision ID: dfd7ba969b8b
Revises: 048fd4a97938
Create Date: 2023-12-18 09:42:20.583278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd7ba969b8b'
down_revision: Union[str, None] = '048fd4a97938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('uid', sa.String(), server_default='', nullable=False))
    op.add_column('datasets', sa.Column('date_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('datasets', sa.Column('date_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('datasets', sa.Column('url', sa.String(), nullable=True))
    op.add_column('datasets', sa.Column('accessibility', sa.String(), nullable=True))
    op.drop_index('ix_datasets_bbox_srid', table_name='datasets', postgresql_using='gist')
    op.create_unique_constraint('unique_name_uid', 'datasets', ['name', 'uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name_uid', 'datasets', type_='unique')
    op.create_index('ix_datasets_bbox_srid', 'datasets', [sa.text('st_setsrid(bbox, 4326)')], unique=False, postgresql_using='gist')
    op.drop_column('datasets', 'accessibility')
    op.drop_column('datasets', 'url')
    op.drop_column('datasets', 'date_end')
    op.drop_column('datasets', 'date_start')
    op.drop_column('datasets', 'uid')
    # ### end Alembic commands ###
