PROJECT_NAME='Worldex API (local)'
VERSION=0.1.0
DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB_NAME}
DATABASE_URL_SYNC=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_LOCALHOST}/${POSTGRES_DB_NAME}
